### PR TITLE
Incremental Compiler v2

### PR DESCRIPTION
**Pull request by Apanatshka**
This is the new incremental compiler design for Stratego. The general idea is still the same: 1 `Front` task per file, 1 `Back` task per strategy (generating one or more Java files). However, this one integrates the gradual type system written in Stratego, takes into account that all error messages should be recomputed when the relevant file changes (be because error messages have positions in the file), and Pie works better (i.e. with less overhead) when you depend on (parts of) task outputs directly (the old design copied or referred to a lot of data from task output objects in other task inputs). The handling of modules and imports is also improved, using only the `mb.resource` vfs. 

The package structure of the project has changed quite a bit to make things a bit more clearly separated and to be able to easily find things. TaskDefs live in a package `task`, input objects and output objects are each in a separate subpackage (`task.input` and `task.output`). This should allow of easy check if all input/output objects have an equals/hashcode specified for example. Similarly there is a package`function` and `function.output` for serializable (projection) functions to select only part of a task output when depending only on that part of the task output.

The list of TaskDefs is as follows:
- `Front`: Asks for a module AST, extracts some `ModuleData` from that AST which will be used later.
- `Lib`: Asks for a library AST, extracts some `ModuleData` from that AST which will be used later. Minor differences with Front: no injections of standard library into the imports, no need to traverse the AST searching of usage of names. 
- `Resolve`: Starts at the give "main" Stratego module, calls `Front` on it, and resolves the imports transitively from there to discover all modules. Then builds up some `GlobalData` from the `ModuleData` which is used in different places afterwards.
- `CheckModule`: Runs static checks on a module, based on the `ModuleData` and that of the modules are visible through imports. This is currently still transitive imports, but we may drop support of that to improve performance of the compiler. But that might influence other meta-languages that generate Stratego code. Static checks are mostly done in Stratego, although some overlap checks were easier to keep in Java. 
- `InsertCasts`: Called by `CheckModule` to perform the type checks. As a separate task, this can catch unimportant changes to other modules that are imported. But it is unclear whether comparing the input object of `InsertCasts` (containing the whole relevant type environment) is less expensive than the type checking itself. 
- `Check`: Runs `Resolve`, gets the list of all modules, then runs `CheckModule` on each module. This task can be used to get all error messages for a project. 
- `Back`: Runs per strategy definition. This task desugars the strategy, and then generates Java code for it. In the old architecture desugaring was done earlier in the process and cached in Pie, which is no longer necessary now. Late desugaring does means that dynamic rules are only lifted out at this point, which complicates things slightly. So strategies that contribute to the same dynamic rule are bundled into one larger `Back` task instead of being compiled separately. Desugaring output of these dynamic rule `Back` tasks are analysed as well, to be able to generate the `DYNAMIC_CALLS` strategy correctly. 
    Another artefact of desugaring late is that we don't care to pass constructors to the desugaring. Therefore no congruence strategies are generated. Instead we do this in a separate `Back` task for all constructors at once. If this turns out to be costly we can split it up to generate per module or even per constructor.
- `Compile`: The one task to rule them all, this task runs `Check`, stops if there are errors, and otherwise continues to run all the `Back` tasks. It returns a list of the Java files that were written to, as well as non-error messages from `Check`. 

# Migrating to this new code

If you used the old incremental compiler in a Spoofax project, that should continue to work as expected, modulo TODOs below.
If you used the old incremental compiler from Java inside Spoofax 2, you will now need to use Pie TaskDef `Compile` or `Check` instead of `StrIncr` or `StrIncrAnalysis` respectively. See the changes in https://github.com/metaborg/spoofax/pull/78 for examples of how this changed.
If you used the old incremental compiler from Java outside Spoofax 2, you also needed to implement a couple of interfaces. The new (and old) interfaces to implement now are `IModuleImportService` (previously `ParseStratego`), `ResourcePathConverter` (as before).

# TODOs

- [x] StrategoGradualSetting, the metaborg.yaml setting of gradual types (none, static, dynamic) is not fully implemented yet. The `Back` task needs to use the AST from `Front` instead of `CheckModule` to avoid compiling the inserted casts for options none and static. 
- [X] The boilerplate task in Back needs to receive the ASTs defining all constructors and injections, so it can generate code that registers this type information at runtime for the casts.
- [X] Consider folding the old `InsertCasts` task into the `CheckModule` task.
- [x] Check library imports against `-la` arguments that provide the built-in libraries

- [x] Remove `Lib`, `Front` should work just as well on libraries. Then `SplitShared` can be merged into `Front`
- [x] Check if all uses of tasks results use all the fields or if we can use tighter projection functions.
- [x] Check if functions on task outputs that build new information are not called many times, and otherwise cache the result (like is done for e.g. `GlobalIndex`)

# PR Set
- https://github.com/metaborg/spoofax-deploy/pull/35
- https://github.com/metaborg/spoofax/pull/78
- https://github.com/metaborg/strategoxt/pull/36
- https://github.com/metaborg/stratego/pull/15

### CODE REVIEW

**Review by Gohla — CHANGES_REQUESTED** [review]
Very nice! The tasks, their inputs and outputs, and their relations are a lot clearer now. And almost all input objects are also small now. There is still a huge amount of internal details that I do not fully understand, but that is ok. Therefore, my review is a bit on the architecture side, and a lot of smaller issues, mostly regarding `Serializable`/`equals`/`hashCode`.


# IModuleImportService abstraction

A big issue is that the new `IModuleImportService` abstraction/implementation is mixing too many concerns, and would require me to copy-paste a lot of code into Spoofax 3 and keep in sync with Spoofax 2, which is bad. As I understand it, the intent behind `IModuleImportService` is to abstract over how to go from a module name to an AST, which I think is a very useful abstraction. However currently it abstracts over:
* `resolveImport`: go from a term representing and import into something 'resolved'. `ImportResolution` is an empty interface so I am not sure what the purpose is. This seems like an implementation detail that should go into `stratego.build`. It does not differ between Spoofax 2 and 3.
* `getModuleAst`: go from a module ID to an AST. This is a useful abstraction but does not differ between Spoofax 2 and 3.
* `parse`: go from a file/bytes of that file into an ast. This is a useful abstraction and *does* differ between Spoofax 2 and 3. This is exactly what `ParseStratego` used to abstact over.

An additional issue is that `IModuleImportService` requires `Serializable`, but this will never hold. `ModuleImportService` cannot implement `Serializable` because it holds a bunch of Spoofax 2 classes that cannot be serialized. Several classes use this as input, but that will not work. It should be injected into TaskDefs instead. Classes that use it as input:
  * `FrontInput`
  * `ResolveInput`
  * `CheckInput`
  * `BackInput.Normal` and deratives
  * `CompileInput`

I propose to:
* Bring back `ParseStratego` to abstract over the details of how to parse Stratego code, which differs between Spoofax 2 and 3.
* Move the `resolveImport` part as an implementation detail into `stratego.build`.
* Move the `getModuleAst` part as a `ImportResolver` (or whatever name is better) abstraction in `stratego.build`, with an implementation that takes a module ID and include directories as input, which scans the modules/imports and the file system to resolve. It probably calls into `ParseStratego` to get an AST. An additional future implementation may instead resolve modules through different means, for example by directly transforming SDF3->Stratego signatures.

Then the abstraction over Spoofax 2/3 is small again, and we have a separate abstraction on how to resolve modules/imports.


# Smaller details

* If the `Front` task only works on a single module (AST), it does not need to resolve imports right? In that case, `FrontInput` should not take a `IModuleImportService` (which contains include directories and other stuff as well)?
* The `Resolve` task (and thereby also the `Check` task) also takes a `IModuleImportService` but that does not seem to include on which builtin libraries we depend. Isn't that needed to resolve imports into libraries, which is needed for checking?
* `InsertCastsInput` takes a `GTEnvironment` as input, which can be a pretty big. It is also calcualted as part of `CheckModule`. Can it be retrieved via a task so that it is cached as an output and not passed as an input? (I think you may hint to this in your PR description?)
* `WrongASTException` does not provide an informative message. What is wrong and how can we recover from it? Do we expect a client to be able to recover from this at all? If not, it should probably be a `RuntimeException` and should provide debugging information. If we can recover from it, we need to use the `Result` type, because throwing an exception will stop the entire PIE pipeline.
* The descriptions of the tasks you wrote in your PR are good documentation for the task definitions, why not add them as JavaDoc to those classes?
* `Collection`/`List`/`Set`/`Map`/etc do not implement `Serializable`. If you use these in a `Serializable` class, it may not always really be serializable. Use `ArrayList`/`HashMap`/etc that implement `Serializable`. In practice, you probably use instances that implement `Serializable`, but it is good to confirm this via the type system.
  * `ResolvedImport`
  * `ModuleData`
  * `GlobalData`
  * `CheckModuleOutput`
  * `BackInput`
  * Deratives of `CompileOutput`
* Several `Function`s do unchecked casts that do not always hold for any `T`. This can cause ClassCast/NoMethodFound/etc exceptions in user code that uses the returned value, because the cast is unchecked, which should be avoided at all cost. The generic can just be removed and replaced with a concrete type?
  * `AllModulesIdentifiers`
  * `GetStrategyAnalysisData`
  * `ModulesDefiningDynamicRule`
  * `ModulesDefiningOverlays`
  * `ModulesDefiningStrategy`
* Several `Function`s that are passed to `OutputStampers.funcEquals` do not implement `equals`/`hashCode`, meaning they will be inequal after serialization (also see note about singletons and serialization below):
  * `AllModulesIdentifiers`
  * `GetMessages`
  * `ModulesDefiningOverlays`
  * `ModulesDefiningStrategy`
  * `ToAnnoDefs`
  * `ToGlobalIndex`
  * `ToModuleIndex`
  * `ToOverlays`
* Several `Serializable` classes that are also singletons will always be inequal after serialization, because the singleton pattern is not upheld after deserialization. See last section for a pattern that always works. The following classes suffer from this:
  * `UnresolvedImport`
  * `AllModulesIdentifiers`
  * `GetMessages`
  * `ToGlobalIndex`
  * `ToModuleIndex`
* `CheckInput` does not use `ignoreTypeMessages` in equals/hashcode. Is that intended?
* `Message`
  * Does not use `lastModified` in equals/hashcode. Is that intended?
  * Why is it generic over the type of the location term? It is always `IStrategoTerm`?
* `ResolvedImport` and `UnresolvedImport` do not implement `toString`. I'd recommend implementing `toString` for these kind of data classes to make debugging easier.
* What is the difference between `BuiltinLibraryIdentifier` and `ModuleIdentifier` with `isLibrary` set to `true`?


# Nitpicks

* The do-while loop in `Resolve` can just be a regular while loop. A do-while loop is used when you want to always perform one iteration before checking the condition. That could actually lead to an exception in this case if `workList` was empty (but that is never the case). A while loop would be a simpler construct in my opinion.
* `workList` could be a `Queue` beause the double-ended feature of `Dequeue` is not used.


# hashCode/equals/Serializable pattern for singletons

```java
@Override public boolean equals(Object other) {
  return this == other || other != null && this.getClass() == other.getClass();
}

@Override public int hashCode() { return 0; }

private Object readResolve() { return instance; }
```

**Comment by Apanatshka** [comment]
I think I've processed most of your feedback now. I've also updated my TODO list in the description of the PR. Here are some answers to questions:

> Isn't that needed to resolve imports into libraries, which is needed for checking?

Yes, I forgot to reinclude that. It's now on my TODO list.

> Can [`GTEnvironment`] be retrieved via a task so that it is cached as an output and not passed as an input? (I think you may hint to this in your PR description?)

I've removed `InsertCasts` and let `CheckModule` do that work directly to `GTEnvironment` doesn't become part of any input or output object. Perhaps we'll find later with measurements that this is slow because of re-runs of the type checker on irrelevant changes (that influence something else in `CheckModule`), but then we can split things up again and in a nicer way. But for now let's avoid big objects in inputs/outputs.

> If not, it should probably be a `RuntimeException` and should provide debugging information.

What information would you suggest? (I've switched to `RuntimeException`)

> What is the difference between `BuiltinLibraryIdentifier` and `ModuleIdentifier` with isLibrary set to true?

`BuiltinLibraryIdentifier` is an enum with the specific compiled libraries that are always available in Spoofax as part of Stratego/XT. The ASTs for the external definitions of those are already available in memory and should be obtained that way. `ModuleIdentifier` is for every other module. It currently doesn't support compiled libraries, but it should in the future as in principle it's possible to depend on a compiled Stratego library by using the compiler argument `-la` and pointing to the jar of the compiled library (this is done in WebDSL I believe). Of course this is rather awkward in Spoofax 2 because you will not only need to include the jar somewhere at compile time, but also include the classes from it in your `.spoofax-language` result so it's available at runtime.

**Comment by Gohla** [comment]
Nice! That resolved basically all my feedback.

> I've removed InsertCasts and let CheckModule do that work directly to GTEnvironment doesn't become part of any input or output object.

There's still a `InsertCastsInput` though. It does not seem to be used as an input, but maybe it should be moved outside of the `input` package in that case.

> What information would you suggest? (I've switched to RuntimeException)

Right now it does not produce any message, so it is not very informative for the developers nor users when something goes wrong. Something like:

```
@Override public String getMessage() {
    return "BUG: Invalid AST shape while checking/compiling Stratego module '" + moduleIdentifier + "': " + ast;
}
```

That indicates that it is a bug (i.e., developer error, not user error), explains what is wrong (invalid AST shape), where it goes wrong (in the Stratego compiler, on a particular module), and includes the subject: the invalid AST. The stack trace then gives us a more precise error location. That should be enough to debug the problem.

Also minor nitpick (don't mind if you disagree): "Wrong" is a bit informal. "Invalid" and "Illegal" are typically used in exception names.

Some other issues I found:

* `ConstructorData` is not serializable. Should be serializable because it is used as an output of a `Function`.
* `OverlayData` is not serializable, and has no equals/hashcode implementation.
* `StrategyFrontData` is not serializable, but not sure if it used in PIE.

It would be really good to have some tests for serializability :)

**Comment by Apanatshka** [comment]
> It would be really good to have some tests for serializability :)

Do you have any examples of that? I suppose unit tests are nice to have for easy and quick testing, but then you need to make sure you test all relevant classes. Would it be a roundtrip serialize/deserialize and equals check?
A system test would also be nice where you run a clean compile on a project and then try to serialize the entire store. Is there an API for that?

**Comment by Gohla** [comment]
Having several smoke tests for the compiler that test the general functionality would be good. Then you can for example use `SerializingStore` in PIE to serialize the store when PIE is `close`d, which will throw exceptions when something cannot be serialized. You can also run PIE with `ValidationLayer.all` to enable a lot of (very slow) runtime checks that check the `equals`/`hashCode`/`Serializable` implementations. 

The validation layer will most likely detect many issues if your keys contain `HashSet` or `HashMap`, because the serialized bytes of those objects often differ after a roundtrip because the order is non-deterministic. That is something we need to solve some time as well :P

**Comment by Gohla** [comment]
It's probably not easy to reuse the code, because it uses some parts of Spoofax 3, but I have a simple smoke test for the Stratego compiler in Spoofax 3: https://github.com/metaborg/spoofax-pie/blob/develop/lwb/stratego/stratego/src/test/java/mb/str/CompileTest.java

**Comment by Apanatshka** [comment]
I changed all `HashMap`/`HashSet`s in `Serializable` classes to the `Linked` version that keeps insertion order. That should make the serialised bytes stable. I do wonder if the `capsule` persistent datastructures have a stable serialisation. It doesn't matter for the moment, I don't think I used them in input and output objects, but in case we want to use them in the future...

**Comment by Gohla** [comment]
That works indeed. Not sure what the performance impact is though.

`OverlayData` still does not have an `equals`and `hashCode` implementation.

**Comment by Apanatshka** [comment]
@Gohla Can you have a look at the `key` I added to `Back`. I ran into a problem with Pie failing the build when you changed the gradual types setting in the `metaborg.yaml` file, because then a "different" `Back` task would produce the same file. Any thoughts on if I should add keys to other tasks?

I think you can look at the rest commit by commit, I think I've done better with commit messages and size of commits now. Or go over the functions/inputs/outputs again to check hashcode/equals/serializable, whatever you prefer.

**Review by Gohla — APPROVED** [review]

**Pull request merged**
